/**
 * Static sample report data for demonstration purposes
 * This is NOT generated by AI - it's a pre-built showroom model
 * matching the PRO report design (EKO VIBES EP ONE PILOT).
 */

export const sampleReportData = {
  metadata: {
    scriptTitle: 'EKO VIBES EP ONE PILOT',
    format: 'TV Pilot',
    genres: ['Drama', 'Music', 'Crime'],
    budgetRange: '£30M (High Budget)',
    generatedDate: 'July 6, 2026',
    isSample: true,
  },

  summary: {
    logline: 'A rising Fuji music star navigates the venues, boardrooms and police stations of Lagos as ambition is negotiated across two cities — Lagos and London.',
    estimatedShootDays: 45,
    estimatedBudget: '£30M',
    primaryLocations: ['Lagos, Nigeria', 'London, UK', 'Johannesburg, ZA'],
    castSize: {
      principal: 8,
      supporting: 21,
      extras: '200 to 400',
    },
  },

  territoryRankings: [
    {
      rank: 1,
      territory: 'United Kingdom',
      country: 'United Kingdom',
      score: 76,
      rebatePercentage: '25.5% net (34% gross)',
      estimatedRebate: '£5,737,500',
      culturalTestLikelihood: 'High (85%)',
      infrastructureScore: 'Extremely Established',
      adminComplexity: 'Medium',
      paymentSpeed: 'Via corporation tax return (3 to 6 months)',
      keyAdvantages: [
        'The script\'s twenty London scenes are directly filmable without travel cost',
        'Extremely Established crew base and Soho post-production depth suit a music-heavy drama',
        'AVEC claims through the tax return — the only ranked incentive that is bankable at this budget',
        'No cap on rebate amount',
      ],
      keyRisks: [
        'At £30M this production exceeds the IFTC cap — AVEC applies, a £3.2M difference in net rebate',
        'UK cultural test required',
        'Short daylight Nov–Feb affects night-scene turnaround',
      ],
    },
    {
      rank: 2,
      territory: 'Hungary',
      country: 'Hungary',
      score: 71,
      rebatePercentage: '30% cash rebate',
      estimatedRebate: '£2,250,000',
      culturalTestLikelihood: 'N/A — no cultural test',
      infrastructureScore: 'Established',
      adminComplexity: 'Medium',
      paymentSpeed: 'Slow (6 to 9 months) — basis of its Verify First flag',
      keyAdvantages: [
        '30% cash rebate with no cultural test',
        'Korda/Origo set-build capability suited to an interior-heavy shoot',
        'Extremely deep crew base at significantly lower day rates',
      ],
      keyRisks: [
        'Annual programme cap — registration queue can delay certification',
        'Payment timeline 6 to 9 months after audit — verify before bank financing',
      ],
    },
    {
      rank: 3,
      territory: 'Malta',
      country: 'Malta',
      score: 68,
      rebatePercentage: '40% cash rebate',
      estimatedRebate: '£1,200,000',
      culturalTestLikelihood: 'Low',
      infrastructureScore: 'Growing',
      adminComplexity: 'Low',
      paymentSpeed: 'Fast (post-audit, interim payments available)',
      keyAdvantages: [
        'Highest rate of any ranked territory (40% cash)',
        'Efficient administration and fast payment turnaround',
        'Mediterranean Studios for water and interior work',
      ],
      keyRisks: [
        'Limited crew depth for a production of this scale',
        'Key department heads would need importing',
      ],
    },
  ],

  scriptOrigin: {
    territory: 'Nigeria',
    scenesShare: '76% of scenes set in Lagos',
    incentive: 'No formal production incentive programme',
    currencyAdvantage: '95/100',
    crewDepthTier: 'Growing',
    note:
      'The script lives in Lagos — but Nigeria offers no formal production incentive, so it cannot rank on financial dimensions. The case for a Lagos unit is authenticity and purchasing power: the police station, Fuji venues and street scenes are most authentically captured on location, and sterling stretches dramatically against the naira.',
  },

  comparableProductions: [
    {
      title: 'Gangs of Lagos',
      year: 2023,
      budget: '$3-5M',
      territory: 'Nigeria',
      notes: 'Lagos-set ensemble crime drama with international streamer distribution — proof of the setting\'s market appetite.',
    },
    {
      title: 'Blue Story',
      year: 2019,
      budget: '£1.3M',
      territory: 'UK',
      notes: 'London-set music-culture drama; BFI-backed UK production route with strong theatrical performance.',
    },
    {
      title: 'The Woman King',
      year: 2022,
      budget: '$50M',
      territory: 'South Africa',
      notes: 'West-African story anchored in a rebate territory — the multi-territory structure this report recommends.',
    },
  ],

  grantsAndFunding: [
    {
      name: 'BFI Film Fund — Development',
      territory: 'United Kingdom',
      type: 'Grant',
      amount: 'Up to £250,000',
      deadline: 'Rolling',
      eligibility: 'UK-based filmmakers; cultural relevance to the UK',
      likelihood: 'Medium',
    },
    {
      name: 'Creative Europe MEDIA — TV and Online Content',
      territory: 'Europe',
      type: 'Co-production Grant',
      amount: 'Up to €1,000,000',
      deadline: 'Annual',
      eligibility: 'European co-production with broadcaster attachment',
      likelihood: 'Medium',
    },
    {
      name: 'NFI Hungary — Production Support',
      territory: 'Hungary',
      type: 'Grant',
      amount: 'Varies',
      deadline: 'Quarterly',
      eligibility: 'Hungarian co-production partner required',
      likelihood: 'Medium',
    },
  ],

  festivals: [
    {
      name: 'Africa International Film Festival (AFRIFF)',
      country: 'Nigeria',
      tier: 'Mid-tier',
      deadline: 'Submissions close ~2 months before Nov festival',
      submissionFee: 'Varies',
      notes: 'Oscar-qualifying. Nigeria\'s premier festival — the natural premiere for a Lagos music-industry drama.',
    },
    {
      name: 'BFI London Film Festival',
      country: 'UK',
      tier: 'A-List',
      deadline: 'Final deadline early June',
      submissionFee: '£100',
      notes: 'A-list UK premiere platform aligned with the AVEC production structure recommended in this report.',
    },
    {
      name: 'Durban International Film Festival',
      country: 'South Africa',
      tier: 'Mid-tier',
      deadline: 'Early April',
      submissionFee: 'Varies',
      notes: 'Pan-African positioning; films similar to this production have premiered here.',
    },
  ],

  distributors: [
    {
      name: 'FilmOne Entertainment',
      market: 'Lagos / Pan-African theatrical',
      scouts: 'AFRIFF — your recommended premiere',
      notes: 'Actively scouts AFRIFF and distributes Lagos-set drama theatrically across West Africa.',
    },
    {
      name: 'ARRAY Releasing',
      market: 'US / Global streaming',
      scouts: 'BFI London Film Festival',
      notes: 'Diaspora-focused catalogue and genre match; acquisitions team has a track record of scouting BFI LFF.',
    },
  ],

  financialBreakdown: {
    totalBudget: '£30,000,000',
    scenarios: [
      {
        territory: 'United Kingdom',
        localSpend: '£22,500,000 qualifying spend',
        rebateRate: '34% gross / 25.5% net',
        grossRebate: '£7,650,000',
        netBudget: '£24,262,500',
        roi: '25.5% net',
        notes: 'Paid through the tax system — part of the gross credit is taxed back, which is why the usable rate is 25.5%, not 34%.',
      },
      {
        territory: 'Hungary',
        localSpend: '£7,500,000 allocated',
        rebateRate: '30%',
        grossRebate: '£2,250,000',
        netBudget: '£5,250,000',
        roi: '30%',
        notes: 'Cash rebate: gross and net are the same. Payment 6 to 9 months after audit.',
      },
      {
        territory: 'Malta',
        localSpend: '£3,000,000 allocated',
        rebateRate: '40%',
        grossRebate: '£1,200,000',
        netBudget: '£1,800,000',
        roi: '40%',
        notes: 'Cash rebate: gross equals net. Post-audit payment with interim options.',
      },
    ],
  },

  recommendations: {
    primary: 'United Kingdom',
    rationale:
      'With a £30M budget and a script that lives overwhelmingly in Lagos interiors — offices, a police station, living rooms and Fuji music venues account for 79% of scenes — the optimal structure anchors production in the United Kingdom under AVEC: £22.5M qualifying spend returns an estimated £5.74M net, and the claim-through-tax-return mechanism makes it the only ranked incentive that is bankable at this budget.',
    alternateStrategy:
      'Anchor in the UK, build interiors in Hungary or Malta, and capture Lagos on location — the structure that follows this script rather than fighting it. Nigeria offers no formal incentive; the Lagos unit is an authenticity and currency decision, not a rebate decision.',
  },
};
